repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: "^example/python_example_proto_code/example_proto"
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        exclude: "^example/python_example_proto_code/example_proto"
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        exclude: "^example/python_example_proto_code/example_proto|^tests"
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: "^example/python_example_proto_code/example_proto|^tests"
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports']
        exclude: "^example/python_example_proto_code/example_proto"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      # - id: check-yaml
      - id: debug-statements
      # - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
